#!/usr/bin/env bash
# Write docker-compose.override.yml so the container can reach this Pi's GPIO.
#
# The gpio device nodes differ across Pi models, so this maps only the ones that
# exist. docker compose auto-merges docker-compose.override.yml, so both the
# installer and autopi-update pick it up. No-op on a non-Pi host. Idempotent.
#
#   setup-gpio.sh [REPO_DIR]
set -uo pipefail

REPO_DIR="${1:-/opt/autopi-src}"

is_pi=false
for f in /proc/device-tree/model /sys/firmware/devicetree/base/model; do
  [ -r "$f" ] && tr -d '\0' <"$f" | grep -qi 'raspberry pi' && is_pi=true
done
if [ "$is_pi" != true ]; then
  echo "Not a Raspberry Pi; skipping GPIO passthrough."
  exit 0
fi

devs=()
for d in /dev/gpiomem /dev/gpiomem0 /dev/gpiochip0 /dev/gpiochip4; do
  [ -e "$d" ] && devs+=("$d")
done
if [ "${#devs[@]}" -eq 0 ]; then
  echo "No GPIO devices found; skipping GPIO passthrough."
  exit 0
fi

{
  echo "# Generated by setup-gpio.sh: GPIO passthrough for this Pi."
  echo "services:"
  echo "  autopi:"
  echo "    devices:"
  for d in "${devs[@]}"; do echo "      - \"$d:$d\""; done
} > "$REPO_DIR/docker-compose.override.yml"
echo "Wrote $REPO_DIR/docker-compose.override.yml (${devs[*]})"
