#!/usr/bin/env bash
# Bring up the Waveshare 2-Channel CAN-FD HAT (dual MCP2518FD over SPI) as
# SocketCAN interfaces can0 and can1.
#
# Enables SPI and the mcp251xfd device-tree overlay in the boot config, then
# brings each interface up with the requested bitrate (and data-bitrate for
# CAN-FD). Installs a systemd oneshot service that repeats the "ip link up"
# step on every boot, since the overlay recreates the interfaces but does not
# set their bitrate itself.
#
# Run as root on a Pi appliance with the HAT attached. No-op off a Pi.
# Idempotent: re-running only adds what is missing and re-applies the link
# settings.
#
#   setup-can-waveshare.sh
#
# Environment overrides:
#   CAN_BITRATE       arbitration-phase bitrate, bit/s (default 500000)
#   CAN_DBITRATE      CAN-FD data-phase bitrate, bit/s (default 2000000)
#   CAN_FD            "true" to bring the interfaces up in FD mode (default true)
#   CAN0_INTERRUPT    GPIO the first MCP2518FD's INT line is wired to (default 25)
#   CAN1_INTERRUPT    GPIO the second MCP2518FD's INT line is wired to (default 24)
set -uo pipefail

CAN_BITRATE="${CAN_BITRATE:-500000}"
CAN_DBITRATE="${CAN_DBITRATE:-2000000}"
CAN_FD="${CAN_FD:-true}"
CAN0_INTERRUPT="${CAN0_INTERRUPT:-25}"
CAN1_INTERRUPT="${CAN1_INTERRUPT:-24}"

is_pi=false
for f in /proc/device-tree/model /sys/firmware/devicetree/base/model; do
  [ -r "$f" ] && tr -d '\0' <"$f" | grep -qi 'raspberry pi' && is_pi=true
done
if [ "$is_pi" != true ]; then
  echo "Not a Raspberry Pi; leaving CAN unconfigured."
  exit 0
fi

# Bookworm moved the boot partition to /boot/firmware; older images still use
# /boot directly. Use whichever config.txt actually exists.
CONFIG_TXT="/boot/config.txt"
[ -f /boot/firmware/config.txt ] && CONFIG_TXT="/boot/firmware/config.txt"
if [ ! -f "$CONFIG_TXT" ]; then
  echo "No config.txt found at /boot or /boot/firmware; cannot enable the overlay." >&2
  exit 1
fi

add_config_line() {
  local line="$1"
  grep -qxF "$line" "$CONFIG_TXT" || echo "$line" >> "$CONFIG_TXT"
}

echo "Enabling SPI and the mcp251xfd overlay in ${CONFIG_TXT}"
add_config_line "dtparam=spi=on"
add_config_line "dtoverlay=mcp251xfd,spi0-0,interrupt=${CAN0_INTERRUPT}"
add_config_line "dtoverlay=mcp251xfd,spi0-1,interrupt=${CAN1_INTERRUPT}"

echo "Writing the CAN link-up service (bitrate ${CAN_BITRATE}, dbitrate ${CAN_DBITRATE}, fd=${CAN_FD})"
FD_ARGS=""
[ "$CAN_FD" = "true" ] && FD_ARGS="dbitrate ${CAN_DBITRATE} fd on"

cat > /usr/local/sbin/autopi-can-up <<EOF
#!/usr/bin/env bash
# Generated by setup-can-waveshare.sh. Brings can0/can1 up if the mcp251xfd
# overlay has created them; a missing interface (HAT unplugged, overlay not
# yet applied) is reported but not fatal, so this never blocks boot.
set -u
for iface in can0 can1; do
  if ! ip link show "\$iface" >/dev/null 2>&1; then
    echo "autopi-can-up: \$iface not present, skipping"
    continue
  fi
  ip link set "\$iface" down 2>/dev/null || true
  ip link set "\$iface" type can bitrate ${CAN_BITRATE} ${FD_ARGS}
  ip link set "\$iface" up
  echo "autopi-can-up: \$iface up (bitrate ${CAN_BITRATE}${FD_ARGS:+, }${FD_ARGS})"
done
EOF
chmod 755 /usr/local/sbin/autopi-can-up

cat > /etc/systemd/system/autopi-can.service <<'EOF'
[Unit]
Description=Bring up the Waveshare CAN-FD HAT interfaces
After=sys-subsystem-net-devices-can0.device
Wants=sys-subsystem-net-devices-can0.device

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/autopi-can-up
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable autopi-can.service

if ip link show can0 >/dev/null 2>&1 || ip link show can1 >/dev/null 2>&1; then
  echo "mcp251xfd interfaces already present; applying link settings now."
  /usr/local/sbin/autopi-can-up
else
  echo "Overlay written; can0/can1 will appear after a reboot (the interfaces" \
    "do not exist until the mcp251xfd driver loads at boot)."
fi

echo "CAN setup complete. A reboot is required if this is the first run."
