#!/usr/bin/env bash
# Bring up the Waveshare 2-Channel CAN-FD HAT (dual MCP2518FD over SPI) as
# SocketCAN interfaces can0 and can1.
#
# Enables SPI and the mcp251xfd device-tree overlay in the boot config, then
# brings each interface up with the requested bitrate (and data-bitrate for
# CAN-FD). Installs a systemd oneshot service that repeats the "ip link up"
# step on every boot, since the overlay recreates the interfaces but does not
# set their bitrate itself.
#
# Run as root on a Pi appliance with the HAT attached. No-op off a Pi.
# Idempotent: re-running only adds what is missing and re-applies the link
# settings.
#
#   setup-can-waveshare.sh
#
# Environment overrides:
#   CAN_BITRATE       arbitration-phase bitrate, bit/s (default 500000)
#   CAN_DBITRATE      CAN-FD data-phase bitrate, bit/s (default 2000000)
#   CAN_FD            "true" to bring the interfaces up in FD mode (default true)
#   CAN0_INTERRUPT    GPIO the first MCP2518FD's INT line is wired to (default 25)
#   CAN1_INTERRUPT    GPIO the second MCP2518FD's INT line is wired to (default 13)
#
# The defaults match the Waveshare 2-CH CAN FD HAT in its SPI0 mode (the factory
# config: spi0-0 interrupt 25, spi0-1 interrupt 13). The board's other mode wires
# the channels to SPI1 with interrupts 24 and 23; if yours is set that way, see
# the note printed at the end.
set -uo pipefail

CAN_BITRATE="${CAN_BITRATE:-500000}"
CAN_DBITRATE="${CAN_DBITRATE:-2000000}"
CAN_FD="${CAN_FD:-true}"
CAN0_INTERRUPT="${CAN0_INTERRUPT:-25}"
CAN1_INTERRUPT="${CAN1_INTERRUPT:-13}"
# The MCP2518FD's crystal. The Waveshare 2-Ch CAN-FD HAT uses 40 MHz. This must
# match the board or the bit timing is wrong: classic CAN may still limp along,
# but CAN-FD (which needs tight timing) fails. Some board revisions use 20 MHz;
# set CAN_OSCILLATOR=20000000 if FD will not come up.
CAN_OSCILLATOR="${CAN_OSCILLATOR:-40000000}"

is_pi=false
for f in /proc/device-tree/model /sys/firmware/devicetree/base/model; do
  [ -r "$f" ] && tr -d '\0' <"$f" | grep -qi 'raspberry pi' && is_pi=true
done
if [ "$is_pi" != true ]; then
  echo "Not a Raspberry Pi; leaving CAN unconfigured."
  exit 0
fi

# Bookworm moved the boot partition to /boot/firmware; older images still use
# /boot directly. Use whichever config.txt actually exists.
CONFIG_TXT="/boot/config.txt"
[ -f /boot/firmware/config.txt ] && CONFIG_TXT="/boot/firmware/config.txt"
if [ ! -f "$CONFIG_TXT" ]; then
  echo "No config.txt found at /boot or /boot/firmware; cannot enable the overlay." >&2
  exit 1
fi

add_config_line() {
  local line="$1"
  grep -qxF "$line" "$CONFIG_TXT" || echo "$line" >> "$CONFIG_TXT"
}

echo "Enabling SPI and the mcp251xfd overlay in ${CONFIG_TXT}"
add_config_line "dtparam=spi=on"
# Replace any prior mcp251xfd lines so re-running updates the oscillator or the
# interrupt pins cleanly instead of leaving stale, conflicting overlays behind.
sed -i '/^dtoverlay=mcp251xfd/d' "$CONFIG_TXT"
echo "dtoverlay=mcp251xfd,spi0-0,interrupt=${CAN0_INTERRUPT},oscillator=${CAN_OSCILLATOR}" >> "$CONFIG_TXT"
echo "dtoverlay=mcp251xfd,spi0-1,interrupt=${CAN1_INTERRUPT},oscillator=${CAN_OSCILLATOR}" >> "$CONFIG_TXT"

echo "Writing the CAN link-up service (bitrate ${CAN_BITRATE}, dbitrate ${CAN_DBITRATE}, fd=${CAN_FD})"
# restart-ms auto-recovers the interface from a bus-off (matches the factory
# bring-up), so a wiring glitch does not leave the bus down until a manual reset.
CAN_RESTART_MS="${CAN_RESTART_MS:-1000}"
FD_ARGS=""
[ "$CAN_FD" = "true" ] && FD_ARGS="dbitrate ${CAN_DBITRATE} fd on"

cat > /usr/local/sbin/autopi-can-up <<EOF
#!/usr/bin/env bash
# Generated by setup-can-waveshare.sh. Brings can0/can1 up if the mcp251xfd
# overlay has created them; a missing interface (HAT unplugged, overlay not
# yet applied) is reported but not fatal, so this never blocks boot.
set -u
for iface in can0 can1; do
  if ! ip link show "\$iface" >/dev/null 2>&1; then
    echo "autopi-can-up: \$iface not present, skipping"
    continue
  fi
  ip link set "\$iface" down 2>/dev/null || true
  if [ -n "${FD_ARGS}" ] && ip link set "\$iface" type can bitrate ${CAN_BITRATE} restart-ms ${CAN_RESTART_MS} ${FD_ARGS} 2>/dev/null; then
    mode="CAN-FD"
  elif ip link set "\$iface" type can bitrate ${CAN_BITRATE} restart-ms ${CAN_RESTART_MS} 2>/dev/null; then
    mode="classic (CAN-FD setup failed; check the CAN_OSCILLATOR value)"
  else
    echo "autopi-can-up: \$iface could not be configured (see: dmesg | grep mcp251)"
    continue
  fi
  ip link set "\$iface" up && echo "autopi-can-up: \$iface up, \$mode, bitrate ${CAN_BITRATE}"
done
EOF
chmod 755 /usr/local/sbin/autopi-can-up

cat > /etc/systemd/system/autopi-can.service <<'EOF'
[Unit]
Description=Bring up the Waveshare CAN-FD HAT interfaces
After=sys-subsystem-net-devices-can0.device
Wants=sys-subsystem-net-devices-can0.device

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/autopi-can-up
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable autopi-can.service

if ip link show can0 >/dev/null 2>&1 || ip link show can1 >/dev/null 2>&1; then
  echo "mcp251xfd interfaces already present; applying link settings now."
  /usr/local/sbin/autopi-can-up
else
  echo "Overlay written; can0/can1 will appear after a reboot (the interfaces" \
    "do not exist until the mcp251xfd driver loads at boot)."
fi

echo "CAN setup complete. A reboot is required if this is the first run."

echo
echo "--- CAN diagnostics ---"
echo "config.txt overlay lines:"
grep -E '^dtparam=spi|^dtoverlay=mcp251xfd' "$CONFIG_TXT" | sed 's/^/  /'
echo "CAN interfaces present:"
ls -1 /sys/class/net/ 2>/dev/null | grep -E '^can[0-9]+$' | sed 's/^/  /' || echo "  none yet (reboot needed)"
echo "mcp251xfd kernel messages (last 12):"
dmesg 2>/dev/null | grep -i mcp251 | tail -12 | sed 's/^/  /' || echo "  none"
echo
echo "If one channel is missing while the other works, the second controller did not"
echo "probe (dmesg shows 'Failed to read Oscillator Configuration Register'):"
echo "  - these defaults are the Waveshare 2-CH CAN FD HAT SPI0 mode (spi0-0 int 25,"
echo "    spi0-1 int ${CAN1_INTERRUPT}). If the board is jumpered to its SPI1 mode, the channels"
echo "    are on spi1 with interrupts 24 and 23 (dtoverlay=spi1-3cs); see the Waveshare"
echo "    wiki 2-CH_CAN_FD_HAT and set CAN0_INTERRUPT/CAN1_INTERRUPT to match."
echo "  - confirm the HAT is seated and no header pin is bent."
echo "If CAN-FD will not come up but classic does, the oscillator is likely wrong:"
echo "  sudo CAN_OSCILLATOR=20000000 bash \$0   # then reboot"
